export enum TOKENS {
  OPEN_OBJECT = "{",
  CLOSE_OBJECT = "}",
  OPEN_ARRAY = "[",
  CLOSE_ARRAY = "]",
  COMMA = ",",
  QUOTE = '"',
  DASH = "-",
  COLON = ":",
  ESCAPE = "\\",
  BACKSPACE = "\b",
  FORM_FEED = "\f",
  LINE_FEED = "\n",
  CAR_RETURN = "\r",
  HORIZONTAL_TAB = "\t",
  HEX = "u",
  STRING = "STRING",
  NUMBER = "NUMBER",
  BOOLEAN = "BOOLEAN",
  NULL = "NULL",
}
